Silence Jetpack option missing notices that appear with WP-cli 1.5.0
Before:

 $ wp-test
 ==> Running rspec tests...
 Running baseline.rb:
 Error: Could not get 'jetpack_active_modules' option. Does it exist?
 Error: Could not get 'jetpack_active_modules' option. Does it exist?
 Cleaning up...
 Finished in 12.35 seconds (files took 11.09 seconds to load)

After:

 $ wp-test
 ==> Running rspec tests...
 Running baseline.rb:
 Cleaning up...
 Finished in 11.91 seconds (files took 11 seconds to load)

This was not an issue with WP-cli before 1.5.0 because it didn't emit
any option missing notices.